version: '3.9'

services:

  db:
    container_name: todo-backend-postgres
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_backend_phoenix_1_7_dev
